### ISSUE TITLE
It's not working for latest vercel

### ISSUE THREAD

**Issue by 3lang3** [glizzykingdreko/Vercel-Attack-Mode-Solver#1]
https://faucet.story.foundation/

**Comment by glizzykingdreko** [comment]
Hi, the repo is not maintained. If you need a solver for the latest version contact me on discord or via mail.

discord: glizzykingdreko
mail: glizzykingdreko@protonmail.com

**Comment by 3lang3** [comment]
@glizzykingdreko  i send email to you and send a friend request on discord.

**Comment by TimurKutsenko** [comment]
@glizzykingdreko Also send request on discord

**Comment by backspacevenkat** [comment]
@glizzykingdreko i send email to you and send a friend request on discord.

@3lang3 or @TimurKutsenko Can you share if you got access to this?

**Comment by TimurKutsenko** [comment]
> [@glizzykingdreko](https://github.com/glizzykingdreko) i send email to you and send a friend request on discord.
> 
> [@3lang3](https://github.com/3lang3) or [@TimurKutsenko](https://github.com/TimurKutsenko) Can you share if you got access to this?

dev only selling now

**Comment by backspacevenkat** [comment]
I am willing to pay, he is not responding. 

@TimurKutsenko @glizzykingdreko

**Comment by LouisDeconinck** [comment]
@3lang3 @TimurKutsenko @backspacevenkat Has @glizzykingdreko gotten back to you? Does there exist a working solution for the Vercel Attack Mode?

**Comment by glizzykingdreko** [comment]
I am replying to all the mail and discord dms
